// ============================================================
// render.js — builds the page from data.js
// Do not edit this file. All content changes go in data.js.
// ============================================================

(function () {
  'use strict';

  const d = SITE_DATA;
  const main = document.getElementById('site-main');

  // ── Helpers ─────────────────────────────────────────────

  function el(tag, attrs, ...children) {
    const node = document.createElement(tag);
    if (attrs) {
      Object.entries(attrs).forEach(([k, v]) => {
        if (k === 'class') node.className = v;
        else if (k === 'html') node.innerHTML = v;
        else node.setAttribute(k, v);
      });
    }
    children.forEach(child => {
      if (child == null) return;
      if (typeof child === 'string') node.appendChild(document.createTextNode(child));
      else node.appendChild(child);
    });
    return node;
  }

  function section(id) {
    const sec = document.createElement('section');
    sec.id = id;
    const inner = el('div', { class: 'section-inner' });
    sec.appendChild(inner);
    return { sec, inner };
  }

  function sectionHeading(text) {
    return el('h2', { class: 'section-heading' }, text);
  }

  // ── Video facade ────────────────────────────────────────

  function videoFacade(youtubeId, label) {
    const wrapper = el('div', { class: 'video-wrapper' });
    const isPlaceholder = !youtubeId || youtubeId.startsWith('YOUTUBE_ID');

    if (isPlaceholder) {
      const ph = el('div', { class: 'video-placeholder' });
      ph.appendChild(el('span', {}, 'Video coming soon'));
      wrapper.appendChild(ph);
      return wrapper;
    }

    const facade = el('div', {
      class: 'video-facade',
      'data-youtube-id': youtubeId,
      role: 'button',
      tabindex: '0',
      'aria-label': label || 'Play video'
    });
    const thumbImg = document.createElement('img');
    thumbImg.alt = label || 'Video thumbnail';
    thumbImg.style.cssText = 'width:100%;height:100%;object-fit:cover;display:block;';
    // YouTube returns a 120x90 grey placeholder (HTTP 200) for missing sizes
    // so onerror never fires. Use onload + naturalWidth check instead.
    const thumbUrls = [
      `https://img.youtube.com/vi/${youtubeId}/maxresdefault.jpg`,
      `https://img.youtube.com/vi/${youtubeId}/hqdefault.jpg`,
      `https://img.youtube.com/vi/${youtubeId}/mqdefault.jpg`,
    ];
    let thumbIdx = 0;
    function tryNextThumb() {
      if (thumbIdx >= thumbUrls.length) return;
      thumbImg.src = thumbUrls[thumbIdx];
      thumbIdx++;
    }
    thumbImg.onload = function() {
      // 120x90 is the grey placeholder — try next size
      if (this.naturalWidth <= 120) tryNextThumb();
    };
    thumbImg.onerror = function() { tryNextThumb(); };
    tryNextThumb();
    facade.appendChild(thumbImg);
    facade.appendChild(el('div', { class: 'play-btn' }));
    wrapper.appendChild(facade);
    return wrapper;
  }

  // ── Work item ────────────────────────────────────────────

  function workItem(item) {
    const div = el('div', { class: 'work-item' });

    // Visual first
    if (item.youtubeId) {
      div.appendChild(videoFacade(item.youtubeId, item.title));
    } else if (item.type === 'link-image') {
      const a = el('a', { href: item.href, target: '_blank', rel: 'noopener', class: 'work-item-link-image' });
      a.appendChild(el('img', { src: item.image, alt: item.title }));
      div.appendChild(a);
    } else if (item.type === 'image') {
      div.appendChild(el('img', { class: 'work-item-image', src: item.image, alt: item.title }));
    }

    // Title
    const titleEl = el('h3', { class: 'work-item-title' });
    if (item.comingSoon) {
      titleEl.innerHTML = `${item.title} <span class="coming-soon-tag">(coming soon)</span>`;
    } else {
      titleEl.textContent = item.title;
    }
    div.appendChild(titleEl);

    if (item.desc)    div.appendChild(el('p', { class: 'work-item-desc' }, item.desc));
    if (item.credits) {
      const creditsWrap = el('div', { class: 'quote-style' });
      creditsWrap.appendChild(el('p', { class: 'work-item-credits', html: item.credits }));
      div.appendChild(creditsWrap);
    }
    if (item.credit) {
      const creditWrap = el('div', { class: 'quote-style' });
      creditWrap.appendChild(el('p', { class: 'work-credit', html: item.credit }));
      div.appendChild(creditWrap);
    }

    return div;
  }


  // ══════════════════════════════════════════════════════════
  // SECTION 1: BIO & REEL
  // Layout: [photo (top-left)] [reel video (right, tall)]
  //         [text  (bot-left)] [                        ]
  // ══════════════════════════════════════════════════════════
  (function renderBio() {
    const { sec, inner } = section('bioandreel');

    const bioPhotoLink = el('a', {
      class: 'lightbox-trigger',
      href: d.bio.photo,
      'aria-label': 'View full size photo'
    });
    bioPhotoLink.appendChild(el('img', {
      class: 'bio-photo',
      src: d.bio.photo,
      alt: d.bio.photoAlt
    }));
    inner.appendChild(bioPhotoLink);

    const textDiv = el('div', { class: 'bio-text' });
    d.bio.paragraphs.forEach(p => textDiv.appendChild(el('p', { html: p })));
    inner.appendChild(textDiv);

    if (d.reel && d.reel.youtubeId) {
      const reelDiv = el('div', { class: 'bio-reel' });
      const reelWrap = el('div', { class: 'video-wrapper reel-embed' });
      const iframe = el('iframe', {
        src: `https://www.youtube.com/embed/${d.reel.youtubeId}?rel=0&modestbranding=1`,
        title: d.reel.label || 'Composer Reel',
        frameborder: '0',
        allow: 'accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture',
        allowfullscreen: ''
      });
      reelWrap.appendChild(iframe);
      reelDiv.appendChild(reelWrap);
      inner.appendChild(reelDiv);
    }

    main.appendChild(sec);
  })();


  // ══════════════════════════════════════════════════════════
  // SECTION 2: ADS
  // ══════════════════════════════════════════════════════════
  (function renderAds() {
    const { sec, inner } = section('ads');
    inner.appendChild(sectionHeading('Music for Ads'));
    const grid = el('div', { class: 'work-grid' });
    d.ads.forEach(item => grid.appendChild(workItem(item)));
    inner.appendChild(grid);
    main.appendChild(sec);
  })();


  // ══════════════════════════════════════════════════════════
  // SECTION 3: TV & FILM
  // ══════════════════════════════════════════════════════════
  (function renderTV() {
    const { sec, inner } = section('tv');
    inner.appendChild(sectionHeading('Music for TV & Film'));
    const grid = el('div', { class: 'work-grid' });
    d.tv.forEach(item => grid.appendChild(workItem(item)));
    inner.appendChild(grid);
    main.appendChild(sec);
  })();


  // ══════════════════════════════════════════════════════════
  // SECTION 4: ORCHESTRAL
  // ══════════════════════════════════════════════════════════
  (function renderOrchestral() {
    const { sec, inner } = section('orchestral');
    inner.appendChild(sectionHeading('Orchestral Compositions'));
    const grid = el('div', { class: 'work-grid' });
    d.orchestral.forEach(item => grid.appendChild(workItem(item)));
    inner.appendChild(grid);
    main.appendChild(sec);
  })();


  // ══════════════════════════════════════════════════════════
  // SECTION 5: RELEASES — 3 col text grid
  // ══════════════════════════════════════════════════════════
  (function renderReleases() {
    const { sec, inner } = section('releases');
    inner.appendChild(sectionHeading('Personal Releases'));
    const grid = el('div', { class: 'releases-grid' });

    d.releases.forEach(item => {
      const div = el('div', { class: 'release-item' });
      const title = el('p', { class: 'release-title' });
      title.innerHTML = `<strong>${item.title}</strong> <em>(${item.year})</em>`;
      div.appendChild(title);
      const meta = el('p', { class: 'release-meta' });
      meta.innerHTML = item.meta + (item.guests ? `<br>${item.guests}` : '');
      div.appendChild(meta);
      if (item.embed) div.appendChild(el('div', { class: 'release-embed', html: item.embed }));
      grid.appendChild(div);
    });

    inner.appendChild(grid);
    main.appendChild(sec);
  })();


  // ══════════════════════════════════════════════════════════
  // SECTION 6: LIBRARIES — 2 col
  // ══════════════════════════════════════════════════════════
  (function renderLibraries() {
    const { sec, inner } = section('libraries');
    inner.appendChild(sectionHeading('Libraries'));
    const grid = el('div', { class: 'libraries-grid' });

    d.libraries.forEach(item => {
      const div = el('div', { class: 'library-item' });
      div.appendChild(el('h3', {}, item.heading));
      const descP = el('p', {});
      descP.innerHTML = `${item.desc} Contact <a href="mailto:${d.contact.email}">${d.contact.email}</a> for further details.`;
      div.appendChild(descP);
      if (item.embed) div.appendChild(el('div', { class: 'library-embed', html: item.embed }));
      grid.appendChild(div);
    });

    inner.appendChild(grid);
    main.appendChild(sec);
  })();


  // ══════════════════════════════════════════════════════════
  // SECTION 7: MEMES
  // ══════════════════════════════════════════════════════════
  (function renderMemes() {
    const { sec, inner } = section('memes');
    inner.appendChild(sectionHeading('Memes'));
    const intro = el('p', { class: 'section-intro' });
    intro.innerHTML = `If you've known me a while, you know that I love to make memes, parody videos, and other silly things in my spare time. No idea is too niche or too time consuming if I want to see it come to life. You can find most of them <a href="https://twisterandjumanji.wordpress.com/" target="_blank" rel="noopener">here</a>, but below are a few that involved some form of music production.`;
    inner.appendChild(intro);
    const grid = el('div', { class: 'work-grid' });
    d.memes.forEach(item => grid.appendChild(workItem(item)));
    inner.appendChild(grid);
    main.appendChild(sec);
  })();


  // ══════════════════════════════════════════════════════════
  // SECTION 8: STUDIO — image left, specs right
  // ══════════════════════════════════════════════════════════
  (function renderStudio() {
    const { sec, inner } = section('studio');

    // Heading spans full width above the two-col layout
    const headingWrapper = el('div', { class: 'studio-heading-wrapper' });
    headingWrapper.appendChild(sectionHeading('Home Studio'));
    inner.appendChild(headingWrapper);

    const studioPhotoLink = el('a', {
      class: 'lightbox-trigger',
      href: d.studio.photo,
      'aria-label': 'View full size studio photo'
    });
    studioPhotoLink.appendChild(el('img', {
      class: 'studio-photo',
      src: d.studio.photo,
      alt: d.studio.photoAlt
    }));
    inner.appendChild(studioPhotoLink);

    const specsDiv = el('div', { class: 'studio-specs' });
    d.studio.specs.forEach(spec => {
      const p = el('p', {});
      p.innerHTML = `<strong>${spec.heading}:</strong> ${spec.text}`;
      specsDiv.appendChild(p);
    });
    inner.appendChild(specsDiv);

    main.appendChild(sec);
  })();


  // ══════════════════════════════════════════════════════════
  // SECTION 9: TESTIMONIALS
  // ══════════════════════════════════════════════════════════
  (function renderTestimonials() {
    const { sec, inner } = section('testimonials');
    inner.appendChild(sectionHeading('Testimonials'));
    const grid = el('div', { class: 'testimonials-grid' });

    d.testimonials.forEach(item => {
      const card = el('div', { class: 'testimonial-card' });
      card.appendChild(el('img', { class: 'testimonial-photo', src: item.photo, alt: item.name }));
      const content = el('div', { class: 'testimonial-content' });
      content.appendChild(el('p', { class: 'testimonial-body' }, item.quote));
      const attr = el('div', { class: 'testimonial-attribution' });
      attr.appendChild(el('strong', {}, item.name));
      attr.appendChild(el('span', {}, item.title));
      content.appendChild(attr);
      card.appendChild(content);
      grid.appendChild(card);
    });

    inner.appendChild(grid);
    main.appendChild(sec);
  })();


  // ══════════════════════════════════════════════════════════
  // SECTION 10: CONTACT
  // ══════════════════════════════════════════════════════════
  (function renderContact() {
    const { sec, inner } = section('contact');
    inner.appendChild(sectionHeading('Contact'));

    const line1 = el('p', { class: 'contact-text' });
    line1.innerHTML = `For all project enquiries, say <a href="mailto:${d.contact.email}">${d.contact.email}</a>`;
    inner.appendChild(line1);

    const line2 = el('p', { class: 'contact-text' });
    const socialLinks = d.contact.social.map(s =>
      `<a href="${s.href}" target="_blank" rel="noopener">${s.label}</a>`
    ).join(' and ');
    line2.innerHTML = `To stay in the loop, you can find me on ${socialLinks}.`;
    inner.appendChild(line2);

    if (d.contact.video) {
      const videoWrap = el('div', { class: 'contact-image' });
      const vid = document.createElement('video');
      vid.src = d.contact.video;
      vid.autoplay = true;
      vid.muted = true;
      vid.loop = true;
      vid.playsInline = true;
      vid.setAttribute('playsinline', '');
      videoWrap.appendChild(vid);
      inner.appendChild(videoWrap);
    }

    main.appendChild(sec);
  })();


  // ══════════════════════════════════════════════════════════
  // FOOTER — dark bg, back to top, acknowledgement, charities
  // ══════════════════════════════════════════════════════════
  (function renderFooter() {
    const footer = document.getElementById('site-footer');

    if (d.footer.acknowledgement1) footer.appendChild(el('p', { class: 'footer-acknowledgement' }, d.footer.acknowledgement1));
    footer.appendChild(el('p', { class: 'footer-charities-note' }, d.footer.charitiesNote));

    const logos = el('div', { class: 'footer-charities' });
    logos.appendChild(el('img', { src: 'images/charities.png', alt: 'ASRC, Australian Conservation Foundation, Australian Red Cross, Lifeline, NAAJA, Oxfam' }));
    footer.appendChild(logos);

    const copy = el('p', { class: 'footer-copy' });
    copy.innerHTML = `&copy; ${new Date().getFullYear()} Terry Mann. All rights reserved.`;
    footer.appendChild(copy);
  })();


  // ══════════════════════════════════════════════════════════
  // INTERACTIONS
  // ══════════════════════════════════════════════════════════

  // ── Lightbox ─────────────────────────────────────────────
  (function initLightbox() {
    const overlay = document.createElement('div');
    overlay.id = 'lightbox-overlay';
    overlay.innerHTML = '<img id="lightbox-img" src="" alt=""><button id="lightbox-close" aria-label="Close">&times;</button>';
    document.body.appendChild(overlay);

    const lbImg = document.getElementById('lightbox-img');
    const close = () => { overlay.classList.remove('open'); lbImg.src = ''; };
    document.getElementById('lightbox-close').addEventListener('click', close);
    overlay.addEventListener('click', e => { if (e.target === overlay) close(); });
    document.addEventListener('keydown', e => { if (e.key === 'Escape') close(); });

    document.addEventListener('click', e => {
      const trigger = e.target.closest('.lightbox-trigger');
      if (!trigger) return;
      e.preventDefault();
      lbImg.src = trigger.href;
      overlay.classList.add('open');
    });
  })();

  // Active nav on scroll — IntersectionObserver watches each section
  (function initActiveNav() {
    const navLinks = document.querySelectorAll('#nav-links a');

    function setActive(id) {
      navLinks.forEach(a => {
        const href = a.getAttribute('href').replace('#', '');
        a.classList.toggle('nav-active', href === id);
      });
    }

    const sections = document.querySelectorAll('section[id]');
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) setActive(entry.target.id);
      });
    }, {
      rootMargin: '-40% 0px -55% 0px', // triggers when section is in middle band of viewport
      threshold: 0
    });

    sections.forEach(sec => observer.observe(sec));
  })();

  // Nav scroll shadow
  const nav = document.getElementById('main-nav');
  window.addEventListener('scroll', () => {
    nav.style.boxShadow = window.scrollY > 10 ? '0 2px 10px rgba(0,0,0,0.25)' : '';
  }, { passive: true });

  // Mobile hamburger
  const toggle = document.querySelector('.nav-toggle');
  const navLinks = document.getElementById('nav-links');
  toggle.addEventListener('click', () => {
    const open = navLinks.classList.toggle('open');
    toggle.setAttribute('aria-expanded', open);
  });
  navLinks.querySelectorAll('a').forEach(a => {
    a.addEventListener('click', () => {
      navLinks.classList.remove('open');
      toggle.setAttribute('aria-expanded', false);
    });
  });

  // Video click-to-play
  document.addEventListener('click', handleVideo);
  document.addEventListener('keydown', e => {
    if (e.key === 'Enter' || e.key === ' ') handleVideo(e);
  });

  function handleVideo(e) {
    const facade = e.target.closest('.video-facade');
    if (!facade) return;
    if (e.type === 'keydown') e.preventDefault();
    const id = facade.dataset.youtubeId;
    if (!id || id.startsWith('YOUTUBE_ID')) return;
    const iframe = document.createElement('iframe');
    iframe.src = `https://www.youtube.com/embed/${id}?autoplay=1&rel=0`;
    iframe.setAttribute('frameborder', '0');
    iframe.setAttribute('allow', 'accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture');
    iframe.setAttribute('allowfullscreen', '');
    iframe.setAttribute('title', facade.getAttribute('aria-label') || 'YouTube video');
    facade.parentNode.replaceChild(iframe, facade);
  }

})();
